repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools
          - types-requests
          - numpy
          - "pandas-stubs>=2.0.0.230"
        args:
          - --ignore-missing-imports
          - --install-types
          - --non-interactive

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=google]  # or numpy

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=5000"]  # 5 MB threshold

  # Optional: text/regex checks (useful, but not required)
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: text-unicode-replacement-char
